server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventzen_database
    username: root
    password: Samsu@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: sonalirao123456789sonalirao123456789sonalirao123456789
  expiration: 86400000 # 24 hours in milliseconds